events {}
user www-data www-data;
http {
    server {
        include /etc/nginx/mime.types;
        # listen 443 ssl;
        # ssl_certificate /etc/letsencrypt/live/aluminis.net/fullchain.pem;
        # ssl_certificate_key /etc/letsencrypt/live/aluminis.net/privkey.pem;
        # server_name  aluminis.net;

        location /api {
            # try to serve file directly, fallback to index.php
            try_files $uri /server/public/index.php$is_args$args;
        }

        location ~ ^/server/public/index\.php(|$) {
            fastcgi_pass unix:/var/run/php/php8.5-fpm.sock;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT /var/www/html;
            internal;
        }

        location / {
            root /var/www/html/client/public;
            try_files $uri$args $uri$args/ /index.html;
        }

        error_log stderr;
        access_log /dev/stdout;
    }
}